# Generated by Django 2.2.1 on 2019-05-15 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vwi', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Events',
            new_name='Event',
        ),
        migrations.AlterField(
            model_name='alumni',
            name='image',
            field=models.ImageField(upload_to=''),
        ),
    ]
